# Generated by Django 5.1.4 on 2025-02-19 09:45

import django.db.models.deletion
import modelcluster.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_stationchanneldispatchstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulsoWebConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('wsdl_url', models.CharField(max_length=255, verbose_name='WSDL URL')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('station_id', models.CharField(max_length=255, verbose_name='Station ID')),
                ('duration', models.IntegerField(default=1440, verbose_name='Duration')),
                ('parameter_type', models.CharField(default='H', max_length=100, verbose_name='Parameter Type')),
            ],
            options={
                'verbose_name': 'PulsoWeb Connection',
                'verbose_name_plural': 'PulsoWeb Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='PulsoWebStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('pulsoweb_station_id', models.CharField(max_length=255, verbose_name='Station ID')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Station Timezone')),
            ],
            options={
                'verbose_name': 'PulsoWeb Station Link',
                'verbose_name_plural': 'PulsoWeb Station Links',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='PulsoWebVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('pulsoweb_parameter_name', models.CharField(max_length=255, verbose_name='Pulsoweb Parameter Name')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('network_pulsoweb', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_pulsoweb_plugin.pulsowebconnection')),
                ('pulsoweb_parameter_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Pulsoweb Parameter Unit')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
