# Generated by Django 5.1.4 on 2025-02-20 13:14

import django.db.models.deletion
import modelcluster.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_alter_dispatchchannel_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulsoWebConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('api_base_url', models.CharField(max_length=255, verbose_name='API Base URL')),
                ('api_token', models.CharField(max_length=255, verbose_name='API Token')),
            ],
            options={
                'verbose_name': 'PulsoWeb Connection',
                'verbose_name_plural': 'PulsoWeb Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='PulsoWebStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('pulsoweb_station_code', models.CharField(max_length=255, verbose_name='PulsoWeb Station ID')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Station Timezone')),
            ],
            options={
                'verbose_name': 'PulsoWeb Station Link',
                'verbose_name_plural': 'PulsoWeb Station Links',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='PulsoWebVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('pulsoweb_parameter_code', models.CharField(max_length=255, verbose_name='Pulsoweb Parameter Code')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('network_pulsoweb', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_pulsoweb_plugin.pulsowebconnection')),
                ('pulsoweb_parameter_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='Pulsoweb Parameter Unit')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
