# Generated by Django 5.1.4 on 2025-03-04 17:46

import adl_pulsoweb_plugin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_pulsoweb_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsowebstationlink',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date for data pulling. Select a past date to include the historical data. Leave blank for collecting realtime data only', null=True, validators=[adl_pulsoweb_plugin.validators.validate_start_date], verbose_name='Start Date'),
        ),
    ]
