# Generated by Django 5.1.4 on 2025-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_pulsoweb_plugin', '0002_pulsowebstationlink_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsowebstationlink',
            name='pulsoweb_station_code',
            field=models.PositiveIntegerField(verbose_name='PulsoWeb Station ID'),
        ),
    ]
