# Generated by Django 5.1.9 on 2025-08-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_pulsoweb_plugin', '0003_alter_pulsowebstationlink_pulsoweb_station_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsowebconnection',
            name='api_base_url',
            field=models.CharField(default='https://app.pulsonic.com/rest', max_length=255, verbose_name='API Base URL'),
        ),
    ]
