# Generated by Django 5.1.9 on 2025-08-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_pulsoweb_plugin', '0004_alter_pulsowebconnection_api_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulsowebstationlink',
            name='timezone',
        ),
    ]
